# Generated by Django 4.1 on 2022-08-12 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("SMALL", "small"),
                            ("MEDIUM", "medium"),
                            ("LARGE", "large"),
                            ("EXTRA_LARGE", "extraLarge"),
                        ],
                        default="SMALL",
                        max_length=20,
                    ),
                ),
                (
                    "ordr_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("IN_TRANSIT", "inTransit"),
                            ("DELIVERED", "delivered"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
