# Generated by Django 4.1 on 2022-08-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="ordr_status", new_name="order_status",
        ),
    ]
